# -*- coding: utf-8 -*-
"""M-CocaCola _Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yieX73AcNW82z8We5gYpdHgAPzXyoR-P
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv('/content/coca_cola_sales_data.csv')
df.head(10)

df['Invoice Date']=pd.to_datetime(df['Invoice Date'], errors='coerce')
df['Operating Margin']= df['Operating Margin'].astype(str).str.replace('%','').astype(float) / 100

for col in ['Price per Unit','Units Sold','Total Sales','Operating Profit']:
  df[col] =df[col].replace(r'[\$,]','', regex=True).astype(float)

df.info()

"""# 1️⃣ Sales Trends Over Time 📈
______________________________
### *Question : What seasonal trends can be observed in Coco-Cola Sales, and how can they be leveraged for better forecasting?*
"""

from matplotlib.typing import LineStyleType
# Lets group sales by month.

df['Invoice_With_Month'] = df['Invoice Date'].dt.to_period('M') #invoice with month
monthly_sales=df.groupby('Invoice_With_Month')['Total Sales'].sum() # now group by monthly to get the sum of total sale monthwise.

# Lets plot the graph

plt.figure(figsize=(10,6))
monthly_sales.plot(marker='o', linestyle='-')

plt.title('Coca-Cola Sales Trend',fontsize=14)
plt.xlabel('Invoice Amount by Month',fontsize=14)
plt.ylabel('Total Sale ($)',fontsize=14)
plt.grid()

"""📈 Key Insights from the Coca-Cola Sales Trend

1️⃣ Strong year-over-year growth

-Sales in 2023 are significantly higher than 2022

-Early 2022 monthly sales stay mostly below $300k

-In 2023, sales frequently exceed $800k–$1M
This suggests major growth, possibly due to expansion, better distribution, or pricing changes.

2️⃣ Sharp jump at the start of 2023

-There is a sudden spike in January 2023

-Sales jump from around $110k (Dec 2022) to ~$750k (Jan 2023)

Coca-Cola sales increased significantly from 2022 to 2023, with a sharp rise at the start of 2023 and peak sales during mid-year months, indicating strong growth and seasonal demand.

3️⃣ Seasonal pattern appears

-Sales peak around mid-year (June–August) in both years

-Highest sales occur in July 2023 (~$1.03M)

This aligns with summer demand, higher beverage consumption and Seasonal promotions.

🧠 Overall Conclusion :

Coca-Cola sales show strong growth from 2022 to 2023, with a notable structural shift at the start of 2023 and clear seasonal peaks during mid-year months. The data suggests improved performance rather than random fluctuation.

# 2️⃣ Regional Performance 🌏
_____________________________
### *Question: Which regions contribute the highest and lowest revenue, and what factors drive these differences?*
"""

df.head()

# Aggregate Sales by Region

Regional_sales = df.groupby('Region')['Total Sales'].sum().sort_values(ascending=False)

#Plot the graph

plt.figure(figsize=(10,6))
Regional_sales.plot(kind='bar', color='royalblue')


plt.title('Total Sales By Region', fontsize=14)
plt.xlabel('Regions', fontsize=12)
plt.ylabel('Total Sale ($)', fontsize=12)
plt.xticks(rotation=45)

"""# Key Insights from Regional Sales Analysis:

1. Replicate High-Performing Strategies from the West
The West’s strong performance suggests successful pricing, marketing, or customer engagement strategies. Identifying and scaling these best practices to other regions could drive overall revenue growth.

2. Focus on Upside Potential in Mid-Tier Regions
The Northeast, Southeast, and South show steady but not peak performance. Small improvements in customer acquisition, product mix, or regional promotions could generate significant incremental revenue.

3. Prioritize Targeted Investment in the Midwest
Lower sales in the Midwest indicate an opportunity rather than just underperformance. Market research, localized campaigns, or improved distribution could unlock untapped demand and balance regional revenue contribution.

# 3️⃣ Products Profitability 🥤
______________________________
### *Question: Which beverage brands generate the highest operating profit, and how can Coca-Cola optimize its product mix?*
"""

# Group by Beverage Band

beverage_band=df.groupby('Beverage Brand')['Operating Profit'].sum().sort_values(ascending=False)

# Plot the graph

plt.figure(figsize=(10,6))
beverage_band.plot(kind='bar', color='orange')
plt.title('Product Profitability ')
plt.xlabel('Products')
plt.ylabel('Total Profit ($)')
plt.xticks(rotation=45)

"""# Insights from Beverage Brand Profitability Analysis:

**1.Top Profitable Brands**

Some Coca-Cola beverage brands generate significantly higher operating profit, making them key drivers of revenue.

**2.Low-Profit Brands**

Certain brands contribute less to profitability, indicating either low sales, high costs, or aggressive discounting.

## Business Strategy

*   Focus marketing & distribution on top-performing brands.
*   Evaluate price adjustments or cost-cutting for lower-margin brands.
*   Optimize production and promotion strategies to maximize overall profitability.

# 4️⃣ Product Price Vs Sales Relationship $📈
____________________________________________
### *Question: How does price per unit impact the number of units sold, and is there an optimal price point for maximizing revenue?*
"""

plt.figure(figsize=(10,6))
sns.scatterplot(x=df['Price per Unit'],y= df['Units Sold'],alpha=0.2, color='purple')
plt.title('Price Vs Units Sold', fontsize=14)
plt.xlabel('Price per unit($)',fontsize=12)
plt.ylabel('No. of Units Sold',fontsize=12)
plt.grid(True)

#plt.scatter(df['Price per Unit'], df['Units Sold'],alpha=0.2, color='purple')

"""# Insights from Price vs. Sales Analysis

**Inverse Relationship**

Generally, higher prices lead to lower units sold, which is expected due to price sensitivity.

**Optimal Pricing Points**

There may be price points where sales are maximized, which Coca-Cola can leverage.

## Business Strategy



* Conduct pricing experiments to find the sweet spot between volume and revenue.
* Dynamic pricing based on demand trends and seasonal factors.
* Promotions and discounts to boost sales in price-sensitive segments.

# 5️⃣ Profitability by Price Range 💰📊  
______________________________________
### *Question: Which price segment contributes the most to Coca-Cola’s total profitability, and how should pricing strategies be adjusted?*
"""

# Create Price bins

df['Price Range']=pd.cut(df['Price per Unit'], bins=[0,0.3,0.5,0.7,0.9,1.1], labels=['Low','Mid-Low','Mid','Mid_High','High'])

# Aggregate total profit by price range
price_profit = df.groupby("Price Range")["Operating Profit"].sum()

# Plot price range vs. profit
plt.figure(figsize=(10, 6))
price_profit.plot(kind="bar", color="green")

plt.title("Profitability by Price Range", fontsize=14)
plt.xlabel("Price Range", fontsize=12)
plt.ylabel("Total Operating Profit ($)", fontsize=12)
plt.xticks(rotation=45)

"""# Insights from Price Range vs. Profitability Analysis:

**Most Profitable Price Range**

Coca-Cola generates the **highest operating profit** in a specific price range, suggesting an **ideal pricing zone** for maximizing profit.

**Low-Profit Price Ranges**

Some price ranges have significantly lower profitability, indicating **high costs, lower demand, or excessive discounting**.

**Business Strategy**

• **Align product pricing** with the most profitable range.

• **Reduce costs or improve value propositions** for low-profit price points.

• **Optimize promotions** to drive profitability across all pricing segments.

# 6️⃣ Consumer Behavior Analysis 🛒
___________________________________
### *Question: Which cities drive the highest sales, and where are the biggest opportunities for market expansion?*
"""

# Consumer Behavior Analysis: Sales Distribution by City
city_sales = df.groupby("City")["Total Sales"].sum().sort_values(ascending=False).head(10)  # Top 10 cities

# Plot top cities by sales
plt.figure(figsize=(12, 6))
city_sales.plot(kind="bar", color="blue")

plt.title("Top 10 Cities by Sales", fontsize=14)
plt.xlabel("City", fontsize=12)
plt.ylabel("Total Sales ($)", fontsize=12)
plt.xticks(rotation=45)

"""# Key Insights :

**1. Sales Are Concentrated in a Few Top Cities**

New York clearly leads, with San Francisco and Charleston close behind. This indicates that a small number of cities contribute a disproportionate share of total sales.

**2. Mid-Tier Cities Show Strong Expansion Potential**

Cities like Portland, Orlando, and Miami have solid sales but are not yet saturated. With the right push, they could move closer to top-tier performance.

**3. Long-Tail Cities Still Contribute Meaningful Revenue**

Lower-ranked cities such as New Orleans and Seattle generate less sales individually, but collectively represent a stable and reliable revenue base.

### Business Strategy :

• Invest in high-performing cities with additional promotions and distribution expansion.

• Identify and target potential growth cities through new market entry strategies.

•  Customize marketing campaigns based on regional consumer behavior.

# 7️⃣ Market Segmentation Based on Price Sensitivity 🔍
______________________________________________________
### *Question: How do different consumer segments (Budget, Mid-Range, Premium, Luxury) contribute to overall revenue, and how should Coca-Cola tailor its marketing strategies?*
"""

# Segmenting consumers based on price sensitivity
df["Consumer Segment"] = pd.cut(df["Price per Unit"],
                                bins=[0, 0.3, 0.6, 0.9, 1.2],
                                labels=["Budget", "Mid-Range", "Premium", "Luxury"])

# Aggregate sales by consumer segment
segment_sales = df.groupby("Consumer Segment")["Total Sales"].sum()

# Plot sales distribution across consumer segments
plt.figure(figsize=(10, 6))
segment_sales.plot(kind="bar", color="darkred")

plt.title("Market Segmentation: Sales by Consumer Segment", fontsize=14)
plt.xlabel("Consumer Segment", fontsize=12)
plt.ylabel("Total Sales ($)", fontsize=12)
plt.xticks(rotation=45)

"""# Insights from Market Segmentation

**Mid-Range consumers drive the highest sales**

This indicates that Coca-Cola's core audience prefers affordable pricing with good value.

**Premium and Luxury segments contribute less**

Suggesting that high-end pricing strategies may have limited appeal.

**Budget segment still holds significant sales**

Showing a demand for low-cost options.

### ***Business Strategy***

• Double down on Mid-Range pricing, as it's the highest revenue-generating segment.

• Introduce strategic promotions in the Premium segment to increase market penetration.

• Expand budget-friendly options in price-sensitive regions to boost affordability-driven sales.

# 8️⃣ Repeat Purchase & Consumer Loyalty 🤝
__________________________________________
### *Question: Which retailers have the highest repeat purchase frequency, and how can Coca-Cola strengthen long-term retailer relationships?*
"""

retailer_purchase = df.groupby('Retailer')['Invoice Date'].nunique().sort_values(ascending=False).head(10)


plt.figure(figsize=(10,6))
retailer_purchase.plot(kind='bar',color='darkgreen')
plt.title("Top 10 Retailers by Repeat Purchases", fontsize=14)
plt.xlabel("Retailer", fontsize=12)
plt.ylabel("Number of Unique Purchase Dates", fontsize=12)
plt.xticks(rotation=45)

"""# Insights from Repeat Purchase Analysis:

1. Certain retailers consistently place multiple orders, indicating strong business relationships and consumer loyalty.

2. Some retailers have fewer repeat purchases, suggesting irregular demand or potential chrun.

3. Retailers with frequent purchases are key partners, playing a crucial role in Coca-Cola's distribution network.

## Business Strategy:

• Strengthen partnerships with top retailers through loyalty incentives or bulk discounts.

• Indentify and re-engage low-frequency retailers with targeted promotional offers.

• Introduce loyalty programs to encourage consistent purchases and strengthen long-term business relationships.

# 9️⃣ Correlation Matrix Insights 🔗📊  
_____________________________________
### *Question- What are the strongest correlations between key metrics (sales, profit, pricing, units sold), and how can they inform data-driven decision-making?*
"""

correlation_matrix=df[["Price per Unit", "Units Sold", "Total Sales", "Operating Profit", "Operating Margin"]].corr()


plt.figure(figsize=(9,6))
sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm',fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix of Key Sales Metrics', fontsize=14)

"""## Insights from the Correlation Matrix

1. **Strong Positive Correlation Between Total Sales & Units Sold**  
   - This is expected, as higher units sold naturally lead to higher total sales.

2. **Moderate Positive Correlation Between Operating Profit & Total Sales**  
   - Suggests that higher sales generally lead to higher profit, but costs might vary.

3. **Negative Correlation Between Price per Unit & Units Sold**  
   - Confirms **price sensitivity**—higher prices tend to reduce units sold.

4. **Weak Correlation Between Price per Unit & Total Sales**  
   - Indicates that **pricing alone doesn’t drive sales**, meaning marketing and distribution strategies also play a key role.

## Business Strategy Based on Correlation Insights

- **Sales volume drives revenue more than price increases**, meaning Coca-Cola should focus on **increasing unit sales** through promotions or better distribution.  
- **Profitability isn’t purely dependent on total sales**, suggesting that **cost efficiency and margin optimization** are also crucial.  
- **Price adjustments should be carefully tested**, as **higher prices reduce demand**, but strategic pricing could maximize revenue.

# Coca-Cola Sales Analysis - Summary Report

## 1. Sales Trends Over Time
- **Insight:** Seasonal peaks indicate high-demand months, while sales dips highlight off-peak periods.
- **Strategy:** Align promotions and inventory planning with demand cycles.

## 2. Regional Performance
- **Insight:** Some regions significantly outperform others in total sales.
- **Strategy:** Expand in weaker regions while maintaining strong regional markets.

## 3. Beverage Profitability
- **Insight:** Certain beverage brands generate higher profits, while others contribute less.
- **Strategy:** Focus marketing efforts and production on high-margin brands.

## 4. Price vs. Sales Relationship
- **Insight:** Higher prices generally reduce demand, confirming price sensitivity.
- **Strategy:** Conduct pricing experiments to balance revenue and demand.

## 5. Profitability by Price Range
- **Insight:** Mid-range pricing is the most profitable segment.
- **Strategy:** Optimize pricing models to align with this key segment.

## 6. Consumer Behavior Analysis
- **Insight:** Certain cities drive higher sales, while smaller cities have untapped potential.
- **Strategy:** Localize marketing efforts to enhance regional demand.

## 7. Market Segmentation Based on Price Sensitivity
- **Insight:** Mid-range consumers generate the highest revenue, while luxury and budget segments have distinct behaviors.
- **Strategy:** Customize marketing strategies for each segment.

## 8. Repeat Purchase & Consumer Loyalty
- **Insight:** Some retailers frequently repurchase, showing strong brand loyalty.
- **Strategy:** Strengthen retailer partnerships through loyalty programs.

## 9. Correlation Matrix Insights
- **Insight:** Sales volume has a stronger impact on revenue than pricing changes.
- **Strategy:** Prioritize volume-driven sales growth with optimal pricing.

---

## Final Business Strategy Recommendations:
- Leverage seasonal peaks through targeted marketing.  
- Optimize pricing strategies to align with consumer sensitivity.  
- Expand in strong regions while improving weaker markets.  
- Focus on high-margin beverage brands for increased profitability.  
- Introduce retailer loyalty programs to drive repeat purchases.  
- Use data-driven insights to maximize revenue growth.  

This summary report provides key insights and actionable strategies, making it valuable for decision-making and a strong portfolio project.
"""